version: '3.8'

services:
  app:
    image: chaouch2/foyer:latest  # Change selon ton nom Docker Hub
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: foyer
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
