services:
  app:
    image: chaouch2/foyer:latest
    ports:
      - "8083:8080"  # Tu as déjà changé le port app → VM
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - mysql
    labels:
      - "prometheus.scrape=true"
      - "prometheus.port=8080"

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: foyer
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
