version: '3.8'

services:
  app:
    image: chaouch2/foyer:latest
    container_name: app
    ports:
      - "8086:8086"  # 8086 = port interne Spring Boot, 8083 = accès externe
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - monitoring

  prometheus:
     dns:
      - 8.8.8.8
      - 8.8.4.4
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Mot de passe admin par défaut

volumes:
  grafana-storage:

networks:
  monitoring:
    driver: bridge
